apiVersion: v1
kind: Service
metadata:
  name: codexa-frontend-service
  namespace: two-tier
spec:
  selector:
    app: codexa-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
